name: split_paired_collection
owner: refinery-platform
description: Split the elements of a Paired Dataset Collection into two distinct outputs.
homepage_url: https://github.com/scottx611x/split-paired-collection
long_description: |
    Splits the elements of a Paired Dataset Collection into two distinct outputs
    Input: Paired Dataset Collection
    Outputs: Two files corresponding to the two elements of said collection
remote_repository_url: https://github.com/scottx611x/split-paired-collection
type: unrestricted 
categories:
    - Convert Formats 
exclude:
    - README.md
    - .travis.yml
    - LICENSE
    - requirements.txt
