sudo: required
language: python
install:
    - pip install -r requirements.txt
script:
    - planemo test
after_success:
    - planemo shed_upload --shed_target toolshed --shed_email $SHED_EMAIL --shed_password $SHED_PASSWORD
notifications:
    email:
        recipients:
            - scottx611x@gmail.com
    on_success: never
