language: python

install:
    - pip install -r requirements.txt
    
script:
    - planemo test

after_success:
    - planemo shed_update --shed_target testtoolshed --shed_email $SHED_EMAIL --shed_password $SHED_PASSWORD

notifications:
    email:
        recipients:
            - scottx611x@gmail.com
    on_success: never
